### ISSUE TITLE
Chapter 31 (I am pretty sure)

### ISSUE THREAD

**Issue by DJPMcG** [KanoComputing/terminal-quest#63]
So in that chapter it tells you to type in "cat" when you are in the basement, but the thing is, it says "cat" won't work where you type. On the other screen it keeps on saying to type in "cat".

It has been doing this since about OS 2.4.0 I'm pretty sure. I have already completed te terminal quest though but it's still an issue.

**Comment by radujipa** [comment]
Closing this as per https://github.com/KanoComputing/terminal-quest/issues/82
